name: Publish VRO Plugin
# Controls when the action will run. 
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # /home/runner/work/vrealize-orchestrator-plugin-for-alb/vrealize-orchestrator-plugin-for-alb
      - name: Check Maven version
        run: |
          echo "Check maven version"
          mvn -version
          echo "Check Home path"
          pwd
          echo "Check Maven local repo location"
          mvn help:effective-settings
