name: Publish VRO Plugin
# Controls when the action will run. 
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check Maven version
        run: |
          echo "Check maven version"
          mvn -version
          
      - name: Check Home location
        run: |
          echo "Check Home location"
          ls $HOME
          echo "Check Home location path.."
          echo $HOME
          
      - name: Copy all external jars befour build VRO plugin.
        run: |
          echo "Installing VRO util jar..."
          echo "Check directory is present or not."
          mkdir -p $HOME/.m2/repository/com
          unzip external_jars.zip -d $HOME/.m2/repository/com/vmware
          ls $HOME/.m2/repository/com/vmware
          echo "VRO util jar installed"
          
      - name: Check All Maven external Jars are Copied.
        run: |
          echo "Check Maven external Jars installed."
          cd $HOME/.m2/repository/com/vmware/
          ls o11n/
          
      - name: Build Maven Plugin
        run: |
          echo "Build Maven Plugin Example"
          mvn clean install --offline
          echo "Maven plugin example build sucessfull."
          
      - name: Check Maven local repository artifacts.
        run: |
          echo "Check Maven local repo artifacts"
          ls $HOME/.m2/repository/
          ls $HOME/.m2/repository/com
          ls $HOME/.m2/repository/com/vmware

